// vue3/src/views/components/form/Form.vue
<script setup lang="ts">
import { computed, ref, onMounted, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import {
  ModelType,
  createInputFiltersFormFields,
  get_form_by_model,
  type inputFilters,
  FormApiError,
  formToBodyData,
  type FieldValue,
  type FormModelType
} from '@/common/types';
import DynamicForm from '@/views/components/form/DynamicForm.vue';
import FormError from '@/views/components/form/FormError.vue';
import API, { fetchRowById } from '@/common/api';
import { useAuthStore } from '@/common/stores/auth';
import { useToast } from 'vue-toastification';

const { t } = useI18n();
const toast = useToast();
const route = useRoute();
const router = useRouter();
const auth_store = useAuthStore();

const model = computed<ModelType>(() => route.params.model as ModelType);
const url = computed<string>(() => route.params.url as string);
const isAdd = computed<boolean>(() => url.value === 'add');

const fieldError = ref<string>('');
const objData = ref<Record<string, FieldValue> | FormModelType>({});
const controls = ref<inputFilters>({} as inputFilters);

watch(
  [model, objData],
  () => {
    controls.value = createInputFiltersFormFields(get_form_by_model(model.value), objData.value as Record<string, FieldValue>);
  },
  { deep: true, immediate: true }
);

onMounted(async () => {
  if (isAdd.value) {
    return;
  }
  try {
    objData.value = await fetchRowById({ model: model.value, id: url.value });
  } catch {
    await router.replace({ path: '/error' });
  }
});

const create_update = async (data: inputFilters) => {
  fieldError.value = '';
  const message = t(isAdd.value ? 'toast.create_success' : 'toast.edit_success', {
    model: t(`models.${model.value}`)
  });
  const body = formToBodyData(data);
  try {
    if (model.value === ModelType.student) {
      body.teacher_id = auth_store.user_id;
    } else if (model.value === ModelType.assignment) {
      body.teacher_id = auth_store.user_id;
      body.student_id = auth_store.student_id;
    }
    await API.post(`${model.value}/${url.value}`, body, { suppressToast: true });
    toast.success(message);
    if (model.value === ModelType.teacher) {
      await router.push('/login');
    } else if (model.value === ModelType.student && isAdd.value) {
      await router.push(`/${ModelType.student}`);
    } else {
      await router.push(`/${ModelType.student}/view/${auth_store.student_id}`);
    }
  } catch (err: unknown) {
    const e = err as FormApiError;
    let intlId = e?.message ?? 'form.error';
    const errors = e?.errors;
    if (Array.isArray(errors) && errors.length > 0 && errors[0]?.field) {
      intlId = `form.label.${errors[0].field}`;
    }
    fieldError.value = intlId;
  }
};
</script>

<template>
  <v-row justify="center">
    <v-col class="d-flex flex-row mt-2 justify-space-around" cols="12" sm="12" md="4">
      <DynamicForm
        v-if="isAdd || (objData && Object.keys(objData).length)"
        :key="`${model}-${url}`"
        :is-add="isAdd"
        :model="model"
        :controls="controls"
        @send-form="create_update"
      />
    </v-col>
  </v-row>
  <FormError :field-error="fieldError" />
</template>

// react/src/components/form/Form.tsx
import { useState, useEffect, useCallback } from 'react';
import { isAxiosError } from 'axios';
import { useNavigate, useParams, Navigate } from 'react-router-dom';
import { FormattedMessage, useIntl } from 'react-intl';
import { Button } from '@mui/material';
import DynamicForm from './DynamicForm';
import MainCard from '../cards/MainCard';
import FormError from '@/components/form/FormError';
import { ModelType, create_form_fields, FormField, get_form_by_model, FieldValue, FormModelType } from '@/lib/types';
import { createOrUpdateRow, fetchRowById } from '@/lib/utils/api';
import { useAppSelector } from '@/lib/store';

export default function Form() {
    const intl = useIntl();
    const navigate = useNavigate();
    const params = useParams() as { id?: string; model?: string };
    const model = params.model as ModelType | undefined;
    const id = params.id ?? 'add';

    const { student_id, user_id } = useAppSelector((state) => state.general);

    const [fieldError, setFieldError] = useState<string | null>(null);
    const [fields, setFields] = useState<FormField[]>([]);
    const [shouldRedirect, setShouldRedirect] = useState(false);

    const modelIsValid = model != null && Object.values(ModelType).includes(model);

    const is_add = id === 'add';

    const setFormFields = useCallback(
        (data: FormModelType | Record<string, FieldValue>) => {
            if (!modelIsValid || model == null) return;
            setFields(create_form_fields(get_form_by_model(model), data as Record<string, FieldValue>));
        },
        [model, modelIsValid]
    );

    const loadData = useCallback(async () => {
        if (!modelIsValid || model == null) return;

        if (is_add) {
            setFormFields({});
            return;
        }

        try {
            const data: FormModelType = await fetchRowById({ model, id });
            setFormFields(data);
        } catch {
            setShouldRedirect(true);
        }
    }, [id, model, is_add, modelIsValid, setFormFields]);

    useEffect(() => {
        void loadData();
    }, [loadData]);

    if (!modelIsValid || model == null) return <Navigate to="/error" replace />;
    if (shouldRedirect) return <Navigate to="/error" replace />;

    const title = intl.formatMessage({ id: `${is_add ? 'form_header_add' : 'form_header_edit'}_${model}` });

    const handleSubmit = async (send_fields: FormField[]) => {
        const data: Record<string, FieldValue> = Object.fromEntries(
            send_fields
                .filter((f) => f.key != null)
                .map<
                    [string, FieldValue]
                >((f) => (typeof f.value === 'string' ? [String(f.key), f.value.trim() === '' ? null : f.value.trim()] : [String(f.key), f.value ?? null]))
        );

        if ([ModelType.student, ModelType.assignment].includes(model)) data.teacher_id = user_id;
        if (model === ModelType.assignment) data.student_id = student_id;

        try {
            const message = intl.formatMessage({ id: is_add ? 'toast.create_success' : 'toast.edit_success' }, { model });
            await createOrUpdateRow({ model, data, id, message });

            if (model === ModelType.teacher) navigate(`/login`);
            else if (model === ModelType.student && is_add) navigate(`/${ModelType.student}`);
            else navigate(`/view/${student_id}`);
        } catch (err: unknown) {
            if (isAxiosError(err)) {
                let intlId = err.response?.data?.message ?? 'form.error';
                const errors = err.response?.data?.errors;
                if (Array.isArray(errors) && errors.length > 0 && errors[0]?.field) intlId = `form.label.${errors[0].field}`;
                setFieldError(intlId);
            } else {
                setFieldError('form.error');
            }
        }
    };

    return (
        <MainCard sx={{ py: 6, maxWidth: '65rem', mx: 'auto', textAlign: 'center' }}>
            <Button size="small" onClick={() => navigate(-1)}>
                <FormattedMessage id="form.button.back" />
            </Button>
            {fields.length > 0 && <DynamicForm title={title} fields={fields} onSubmit={handleSubmit} />}
            {fieldError && <FormError fieldError={fieldError} />}
        </MainCard>
    );
}
