// react/src/components/table/ag-grid/AGTableRenderer.tsx
import { useRef } from 'react';
import { useIntl } from 'react-intl';
import { AgGridReact } from 'ag-grid-react';
import type { ColDef, GridApi, GridReadyEvent } from 'ag-grid-community';

import AssignmentsRenderer from './renderer/AssignmentsRenderer';
import ActionRenderer from './renderer/ActionRenderer';
import { AGTableModelType } from '@/lib/types';
import { useAppSelector } from '@/lib/store';

const defaultColDef: ColDef = {
    resizable: true,
    filter: true,
    sortable: true
};

export default function AGTableRenderer({
    cols,
    rows,
    onExportReady
}: {
    cols: ColDef<AGTableModelType>[];
    rows: AGTableModelType[];
    onExportReady: (fn: (fileName: string) => void) => void;
}) {
    const intl = useIntl();
    const customization = useAppSelector((state) => state.customization);

    const themeClass = customization.navType === 'dark' ? 'ag-theme-quartz-dark' : 'ag-theme-quartz';
    const localizedCols: ColDef<AGTableModelType>[] = cols.map((col) => ({
        ...col,
        headerName: intl.formatMessage({ id: `ag.header.${col.field}` }),
        valueFormatter: col.valueFormatter ?? ((p) => (p.value && typeof p.value === 'object' ? '' : p.value))
    }));

    const gridApiRef = useRef<GridApi<AGTableModelType> | null>(null);

    const onGridReady = (e: GridReadyEvent<AGTableModelType>) => {
        gridApiRef.current = e.api as GridApi<AGTableModelType>;
        onExportReady((fileName: string) => {
            gridApiRef.current!.exportDataAsCsv({
                fileName,
                processCellCallback: (p) => {
                    const v = p.value;
                    if (v == null) return '';
                    if (typeof v === 'object') return JSON.stringify(v);
                    return String(v);
                }
            });
        });
    };
    return (
        <div
            key={themeClass}
            className={themeClass}
            style={{
                height: '38rem',
                width: '100%',
                overflowX: 'auto',
                direction: customization.rtlLayout ? 'rtl' : 'ltr'
            }}
            data-testid="ag-table"
        >
            <AgGridReact<AGTableModelType>
                className={themeClass}
                onGridReady={onGridReady}
                rowData={rows}
                columnDefs={localizedCols}
                defaultColDef={defaultColDef}
                enableRtl={customization.rtlLayout}
                ensureDomOrder
                enableCellTextSelection
                animateRows
                rowHeight={38}
                components={{
                    AssignmentsRenderer,
                    ActionRenderer
                }}
            />
        </div>
    );
}

// vue3/src/views/components/table/ag_table/AGTableRenderer.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { AgGridVue } from 'ag-grid-vue3';
import type { ColDef, GridApi, GridOptions, GridReadyEvent } from 'ag-grid-community';

import ActionRenderer from '@/views/components/table/ag_table/renderer/ActionRenderer.vue';
import AssignmentsRenderer from '@/views/components/table/ag_table/renderer/AssignmentsRenderer.vue';
import { useI18n } from 'vue-i18n';
import type { AGTableModelType } from '@/common/types';
import { useCustomizerStore } from '@/common/stores/customizer';

const { t } = useI18n();

interface Props {
  columns: ColDef[];
  rows: AGTableModelType[];
}
const { columns, rows } = defineProps<Props>();

const customizer = useCustomizerStore();

const themeClass = computed(() => (customizer.actTheme.includes('Dark') ? 'ag-theme-quartz-dark' : 'ag-theme-quartz'));
const localizedCols: ColDef[] = columns.map((col: ColDef) => ({
  ...col,
  headerName: t(`ag.headerName.${col.field as string}`),
  valueFormatter: col.valueFormatter ?? ((p) => (p.value && typeof p.value === 'object' ? '' : p.value))
}));

const gridApi = ref<GridApi | null>(null);

const gridOptions: GridOptions<AGTableModelType> = {
  enableCellTextSelection: true,
  animateRows: true
};

const gridComponents = {
  ActionRenderer,
  AssignmentsRenderer
};

const onGridReady = (params: GridReadyEvent) => {
  gridApi.value = params.api as GridApi;
};

const onFirstDataRendered = () => {
  setTimeout(() => {
    const el = window.document.querySelector('.grid-distributors');
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  }, 500);
};

const defaultColDef: ColDef = {
  resizable: true,
  sortable: true,
  filter: true
};

const exportDataAsCsv = (fileName?: string) =>
  gridApi.value?.exportDataAsCsv({
    fileName,
    processCellCallback: (p) => {
      const v = p.value;
      if (v == null) return '';
      if (typeof v === 'object') return JSON.stringify(v);
      return String(v);
    }
  });
defineExpose({ exportDataAsCsv });
</script>

<template>
  <ag-grid-vue
    v-if="rows"
    :class="themeClass"
    :theme="'legacy'"
    :style="{ height: (rows.length > 10 ? 550 : rows.length > 6 ? 400 : 300) + 'px' }"
    :enable-rtl="customizer.isRtl"
    :column-defs="localizedCols"
    :row-data="rows"
    :row-height="42"
    :default-col-def="defaultColDef"
    :grid-options="gridOptions"
    :components="gridComponents"
    @grid-ready="onGridReady"
    @first-data-rendered="onFirstDataRendered"
  />
</template>
